<a href="https://colab.research.google.com/github/shambhu-shah/DM-DW-lab/blob/main/18cse195_assg2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#MEAN
n_num = [1, 2, 3, 4, 5] 
n = len(n_num) 
  
total_sum = sum(n_num) 
mean = total_sum / n 
  
print("Mean / Average is: " + str(mean))


Mean / Average is: 3.0


#**some basic program in python**

In [ ]:
#swap two variables 

x = 5
y = 10


#x = input('Enter value of x: ')
#y = input('Enter value of y: ')


temp = x
x = y
y = temp

print('The value of x after swapping: {}'.format(x))
print('The value of y after swapping: {}'.format(y))

The value of x after swapping: 10
The value of y after swapping: 5


In [ ]:
# Python Program to calculate the square root


num = 8 



num_sqrt = num ** 0.5
print('The square root of %0.3f is %0.3f'%(num ,num_sqrt))

The square root of 8.000 is 2.828


In [ ]:
# Python Program to find the area of triangle

a = 5
b = 6
c = 7



# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print('The area of the triangle is %0.2f' %area)

The area of the triangle is 14.70


In [ ]:
#median
element = [1, 2, 3, 4, 5] 
n = len(element) 
element.sort() 
  
if n % 2 == 0: 
    median1 = element[n//2] 
    median2 = element[n//2 - 1] 
    median = (median1 + median2)/2
else: 
    median = element[n//2] 
print("Median is: " + str(median)) 

Median is: 3


In [ ]:
#mode

# list of elements to calculate mode
num_list = [21, 13, 19, 13,19,13]

# Print the list
print(num_list)

# calculate the frequency of each item
data = collections.Counter(num_list)
data_list = dict(data)

# Print the items with frequency
print(data_list)

# Find the highest frequency
max_value = max(list(data.values()))
mode_val = [num for num, freq in data_list.items() if freq == max_value]
if len(mode_val) == len(num_list):
   print("No mode in the list")
else:
   print("The Mode of the list is : " + ', '.join(map(str, mode_val)))

[21, 13, 19, 13, 19, 13]
{21: 1, 13: 3, 19: 2}
The Mode of the list is : 13


## write a python code for calculating variance and standard deviation for the set of element

In [ ]:
# variance
test_list = [6, 7, 3, 9, 10, 15] 
  
# printing original list 
print("The original list is : " + str(test_list)) 
  
# Variance of List  
mean = sum(test_list) / len(test_list) 
res = sum((i - mean) ** 2 for i in test_list) / len(test_list) 
  
print("The variance of list is : " + str(res))

The original list is : [6, 7, 3, 9, 10, 15]
The variance of list is : 13.888888888888891


In [ ]:
# standard deviation
test_list = [4, 5, 8, 9, 10] 
  
# printing list 
print("The original list : " + str(test_list)) 
  
# Standard deviation of list 
# Using sum() + list comprehension 
mean = sum(test_list) / len(test_list) 
variance = sum([((x - mean) ** 2) for x in test_list]) / len(test_list) 
res = variance ** 0.5
  
# Printing result 
print("Standard deviation of sample is : " + str(res))

The original list : [4, 5, 8, 9, 10]
Standard deviation of sample is : 2.3151673805580453


#**random operation on data sets**

In [18]:
from google.colab import files
uploaded=files.upload()

Saving indian_food.jpg.csv to indian_food.jpg (1).csv


In [19]:
import pandas as pd
import numpy as np

import io
df=pd.read_csv(io.BytesIO(uploaded['indian_food.jpg.csv']))
df.head()

name  ... region
0      Balu shahi  ...   East
1          Boondi  ...   West
2  Gajar ka halwa  ...  North
3          Ghevar  ...   West
4     Gulab jamun  ...   East

[5 rows x 9 columns]

# **practise 10 python program with numpy library**

In [23]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [24]:
np.intersect1d(n1,n2)

array([50, 60])

In [25]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [26]:
import numpy as np
n1=np.array([10,5])
n2=np.array([30,4])
np.sum([n1,n2])

49

In [28]:
import numpy as np
n1=np.array([10,65])
n2=np.array([30,40])
np.sum([n1,n2],axis=1)

array([75, 70])

In [30]:
import numpy as np
n1=np.array([10,6,4])
n2=np.array([30,40,3])
np.vstack((n1,n2))

array([[10,  6,  4],
       [30, 40,  3]])

In [31]:
import numpy as np
n1=np.array([10,6,4])
n2=np.array([30,40,3])
np.hstack((n1,n2))

array([10,  6,  4, 30, 40,  3])

In [32]:
import numpy as np
n1=np.array([10,6,4])
n2=np.array([30,40,3])
np.column_stack((n1,n2))

array([[10, 30],
       [ 6, 40],
       [ 4,  3]])

In [33]:
import numpy as np
n1=np.array([[1,2,3,3],[4,7,8,9]])
n1.shape

(2, 4)

In [43]:
import numpy as np
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [44]:
import numpy as np
n1=np.array([10,20,30])
n1=n1-2
n1

array([ 8, 18, 28])

In [45]:
import numpy as np
n1=np.array([10,20,30])
n1=n1*4
n1

array([ 40,  80, 120])

**practise 10 question on pandas library**

In [47]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [53]:
import pandas as pd
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[5]

6

In [48]:
import pandas as pd
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [49]:
import pandas as pd
s1=pd.Series({'a':10,'b':3,'c':40})
s1

a    10
b     3
c    40
dtype: int64

In [52]:
import pandas as pd
s1=pd.Series({'a':10,'b':3,'c':40},index=['b','f','e'])
s1

b    3.0
f    NaN
e    NaN
dtype: float64

In [54]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1[:3]

0    1
1    2
2    3
dtype: int64

In [55]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1[:-2]

0    1
1    2
2    3
dtype: int64

In [56]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1+3

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [57]:
import pandas as pd
s1=pd.Series([1,2,3,4,5,6,7,8])
s1*4

0     4
1     8
2    12
3    16
4    20
5    24
6    28
7    32
dtype: int64

In [58]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50,60])
s1+s2

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5     NaN
dtype: float64

In [59]:
import pandas as pd
s1=pd.Series([1,2,3,4,5,6,7,8])
s1-2

0   -1
1    0
2    1
3    2
4    3
5    4
6    5
7    6
dtype: int64